### PR TITLE
Feat support posframe.

### PR DESCRIPTION
**Pull request by kongds**
WechatIMG172214
WechatIMG172213

### CODE REVIEW

**Comment by manateelazycat** [comment]
Thanks for patch.

I can't type anything when popup posframe, maybe something wrong with focus posframe?

**Comment by kongds** [comment]
I use the flag `:accept-focus` in `posframe-show` to allow posframe focus.
However, this seems do not support in previous versions(<0.80) of posframe. Can you try the new version of posframe?

**Comment by manateelazycat** [comment]
> I use the flag `:accept-focus` in `posframe-show` to allow posframe focus. However, this seems do not support in previous versions(<0.80) of posframe. Can you try the new version of posframe?

I have install newest posframe (version 1.1.8), posframe not got focus when popup.

**Comment by kongds** [comment]
I try my emacs (`GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2022-09-16`) with `emacs -Q`,  the posframe of blink-search can get focus.

Can you try the following code ( create a focus posframe )? 
``` emacs-lisp
(select-frame (posframe-show
  (get-buffer-create "*scratch*")
  :poshandler #'posframe-poshandler-frame-center
  :min-height 50
  :min-width  50
  :border-width 2
  :border-color "gray"
  :accept-focus t
  :override-parameters '((cursor-type . box))
 ))
```

**Comment by manateelazycat** [comment]
> I try my emacs (`GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2022-09-16`) with `emacs -Q`, the posframe of blink-search can get focus.
> 
> Can you try the following code ( create a focus posframe )?
> 
> ```emacs-lisp
> (select-frame (posframe-show
>   (get-buffer-create "*scratch*")
>   :poshandler #'posframe-poshandler-frame-center
>   :min-height 50
>   :min-width  50
>   :border-width 2
>   :border-color "gray"
>   :accept-focus t
>   :override-parameters '((cursor-type . box))
>  ))
> ```

No, above code can't work.

You should use `select-frame-set-input-focus` popup frame, like I did in snails: https://github.com/manateelazycat/snails/blob/2ed29a5cf2ae6bc032735b40061f09ae983f9980/snails-core.el#L647

**Comment by kongds** [comment]
I change `select-frame` to `select-frame-set-input-focus`. Can you try again?

**Comment by manateelazycat** [comment]
> I change `select-frame` to `select-frame-set-input-focus`. Can you try again?

Please rebase, otherwise I can't test this PR.

**Comment by manateelazycat** [comment]
> I change `select-frame` to `select-frame-set-input-focus`. Can you try again?

Can got input focus when popup posframe, but still have some problem:
1. When do `blink-search-quit`, Emacs frame lost focus, you should record Emacs frame before popup posframe, when posframe hide, you need call `select-frame` and `select-frame-set-input-focus` on Emacs frame
2. posframe's input buffer not set window margin, please search `(setq-local left-margin-width 1)` and `(setq-local right-margin-width 1)`
3. posframe input buffer can't show cursor, I don't know why. ;)

**Comment by manateelazycat** [comment]
@kongds Focus right after posframe hide, but input buffer's left margin still not right. ;)

**Comment by kongds** [comment]
Thank you for your reply and suggestions.

For problem 1, I have updated code to call `select-frame-set-input-focus` on emacs frame.

For problem 2, I update code to set window margin.

For problem 3,  I'm not quite sure why. I can use the flag and value `  :override-parameters '((cursor-type . box))` in `posframe-show` to show cursor.

Sorry for previous problems like (not focus in posframe, not focus back, not show cursor),  these seem to be caused by different  window systems or window managers.  However, I don't encounter the above problem in my window systems.

**Comment by kongds** [comment]
> @kongds Focus right after posframe hide, but input buffer's left margin still not right. ;)

But i check the local value of input buffer `left-margin-width`, it seems right.
Can you try again after calling `posframe-delete-all` ?
image

**Comment by manateelazycat** [comment]
> > @kongds Focus right after posframe hide, but input buffer's left margin still not right. ;)
> 
> But i check the local value of input buffer `left-margin-width`, it seems right. Can you try again after calling `posframe-delete-all` ? image
截图 2022-11-06 19-48-01

Don't know why my left margin and cursor not works. ;)

**Comment by manateelazycat** [comment]
> > > @kongds Focus right after posframe hide, but input buffer's left margin still not right. ;)
> > 
> > 
> > But i check the local value of input buffer `left-margin-width`, it seems right. Can you try again after calling `posframe-delete-all` ? image
> > 截图 2022-11-06 19-48-01
> 
> Don't know why my left margin and cursor not works. ;)

I got many errors when enable posframe:
```
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])

```

**Comment by kongds** [comment]
I update code of margin (maybe this can work).
For these errors, i can't reproduce them. Can you share how to reproduce these errors?

**Comment by manateelazycat** [comment]
> I update code of margin (maybe this can work). For these errors, i can't reproduce them. Can you share how to reproduce these errors?
截图 2022-11-06 21-31-15

Cursor and margin works great now. ;)

I'm digg why window-live-p error happen.

**Comment by manateelazycat** [comment]
Good enough to merge, I will try fix some errors after merge.

Awesome! ;)

**Comment by kongds** [comment]
Thanks.

But I find a bug that selected buffer will switch to start blink-search-start-buffer.  I will try to fix it.

**Comment by manateelazycat** [comment]
> > > > @kongds Focus right after posframe hide, but input buffer's left margin still not right. ;)
> > > 
> > > 
> > > But i check the local value of input buffer `left-margin-width`, it seems right. Can you try again after calling `posframe-delete-all` ? image
> > > 截图 2022-11-06 19-48-01
> > 
> > 
> > Don't know why my left margin and cursor not works. ;)
> 
> I got many errors when enable posframe:
> 
> ```
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ERROR:epc:ReturnError([Symbol('wrong-type-argument'), Symbol('window-live-p'), 'blink-search.el'])
> ```

I have fix window-live-p error by commit https://github.com/manateelazycat/blink-search/commit/b942bdc8442409682f324bfe047374b3f725fafd

The key is https://github.com/manateelazycat/blink-search/blob/b942bdc8442409682f324bfe047374b3f725fafd/blink-search.el#L790

We should use `with-selected-frame` select posframe frame first, can't use `set-window-buffer`, because it works on emacs frame, not posframe frame.

**Comment by kongds** [comment]
But I want to show start-buffer in emacs frame (posframe is too small to show start-buffer and backends).
the `blink-search-preview`  makes  backend and start buffer uses same window in posframe.
https://github.com/manateelazycat/blink-search/blob/4d8e95cad0ec7ef6baa52c4241fc04d4cf9d0df9/blink-search.el#L791-L792
like this
image

**Comment by manateelazycat** [comment]
> But I want to show start-buffer in emacs frame (posframe is too small to show start-buffer and backends). the `blink-search-preview` makes backend and start buffer uses same window in posframe.
> 
> https://github.com/manateelazycat/blink-search/blob/4d8e95cad0ec7ef6baa52c4241fc04d4cf9d0df9/blink-search.el#L791-L792
> 
> 
> like this
> image

Welcome to send new PR, I just want fix window-live-p error (start posframe will occur), my last commit perhaps bring wrong behavior.

**Comment by kongds** [comment]
> Thanks.
> 
> But I find a bug that selected buffer will switch to start blink-search-start-buffer. I will try to fix it.

Ok 
Can you switch-buffer with blink-search posframe ? I find with posframe using blink-search to switch buffer will switch back to start buffer.

**Comment by manateelazycat** [comment]
> > Thanks.
> > But I find a bug that selected buffer will switch to start blink-search-start-buffer. I will try to fix it.
> 
> Ok Can you switch-buffer with blink-search posframe ? I find with posframe using blink-search to switch buffer will switch back to start buffer.

Best way is use `make-frame` instead posframe, you can research my another plugin snails: https://github.com/manateelazycat/snails/blob/2ed29a5cf2ae6bc032735b40061f09ae983f9980/snails-core.el#L765

make-frame haven't those limit, posframe only useful show text, not handy for search framework.

**Comment by kongds** [comment]
Get it. Anyway thank you for your advice.

**Pull request merged**
